<a href="https://colab.research.google.com/github/Kokila412/ML-project/blob/main/Copy_of_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data=pd.read_csv('https://raw.githubusercontent.com/Kokila412/ML-project/refs/heads/main/Titanic-Dataset.csv')

In [ ]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
travelAlone      0
dtype: int64

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,travelAlone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [ ]:
data['travelAlone']=np.where(((data['SibSp']+data['Parch'])>0),0,1).astype('uint8')

In [ ]:
newData=data.drop(['PassengerId','Name','Ticket','Cabin','SibSp','Parch'],axis=1)

In [ ]:
df_titanic=pd.get_dummies(newData,columns=['Pclass','Sex','Embarked'],drop_first=True)

In [ ]:
df_titanic.head()

,Survived,Age,Fare,travelAlone,Pclass_2,Pclass_3,Sex_male,Embarked_Q,Embarked_S
0,0,22.0,7.2500,0,False,True,True,False,True
1,1,38.0,71.2833,0,False,False,False,False,False
2,1,26.0,7.9250,1,False,True,False,False,True
3,1,35.0,53.1000,0,False,False,False,False,True
4,0,35.0,8.0500,1,False,True,True,False,True

In [ ]:
newData.head()

   Survived  Pclass     Sex   Age     Fare Embarked  travelAlone
0         0       3    male  22.0   7.2500        S            0
1         1       1  female  38.0  71.2833        C            0
2         1       3  female  26.0   7.9250        S            1
3         1       1  female  35.0  53.1000        S            0
4         0       3    male  35.0   8.0500        S            1

In [ ]:
# prompt: fill the empty data in age column in newData with median values

median_age = newData['Age'].median()
newData['Age'].fillna(median_age, inplace=True)

<ipython-input-48-e4c0fc578026>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  newData['Age'].fillna(median_age, inplace=True)

In [ ]:
newData.isnull().sum()

Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
Embarked       2
travelAlone    0
dtype: int64

In [ ]:
x=df_titanic.drop(['Survived'],axis=1)
y=df_titanic['Survived']

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [ ]:
trans_MM=MinMaxScaler()
trans_SS=StandardScaler()

In [ ]:
df_MM=trans_MM.fit_transform(x)
pd.DataFrame(df_MM)

            0         1    2    3    4    5    6    7
0    0.271174  0.014151  0.0  0.0  1.0  1.0  0.0  1.0
1    0.472229  0.139136  0.0  0.0  0.0  0.0  0.0  0.0
2    0.321438  0.015469  1.0  0.0  1.0  0.0  0.0  1.0
3    0.434531  0.103644  0.0  0.0  0.0  0.0  0.0  1.0
4    0.434531  0.015713  1.0  0.0  1.0  1.0  0.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...
886  0.334004  0.025374  1.0  1.0  0.0  1.0  0.0  1.0
887  0.233476  0.058556  1.0  0.0  0.0  0.0  0.0  1.0
888       NaN  0.045771  0.0  0.0  1.0  0.0  0.0  1.0
889  0.321438  0.058556  1.0  0.0  0.0  1.0  0.0  0.0
890  0.396833  0.015127  1.0  0.0  1.0  1.0  1.0  0.0

[891 rows x 8 columns]

In [ ]:
df_SS=trans_SS.fit_transform(x)
pd.DataFrame(df_SS)

,0,1,2,3,4,5,6,7
0,-0.530377,-0.502445,-1.231645,-0.510152,0.902587,0.737695,-0.307562,0.619306
1,0.571831,0.786845,-1.231645,-0.510152,-1.107926,-1.355574,-0.307562,-1.614710
2,-0.254825,-0.488854,0.811922,-0.510152,0.902587,-1.355574,-0.307562,0.619306
3,0.365167,0.420730,-1.231645,-0.510152,-1.107926,-1.355574,-0.307562,0.619306
4,0.365167,-0.486337,0.811922,-0.510152,0.902587,0.737695,-0.307562,0.619306
...,...,...,...,...,...,...,...,...
886,-0.185937,-0.386671,0.811922,1.960202,-1.107926,0.737695,-0.307562,0.619306
887,-0.737041,-0.044381,0.811922,-0.510152,-1.107926,-1.355574,-0.307562,0.619306
888,NaN,-0.176263,-1.231645,-0.510152,0.902587,-1.355574,-0.307562,0.619306
889,-0.254825,-0.044381,0.811922,-0.510152,-1.107926,0.737695,-0.307562,-1.614710
890,0.158503,-0.492378,0.811922,-0.510152,0.902587,0.737695,3.251373,-1.614710